FROM nvcr.io/nvidia/pytorch:24.06-py3

# Automatically generated by the CM workflow automation meta-framework
# https://github.com/mlcommons/ck

LABEL github=""
LABEL maintainer=""
LABEL license=""

SHELL ["/bin/bash", "-c"]

ARG UID=1000
ARG GID=1000
ARG CM_GH_TOKEN


# Notes: https://runnable.com/blog/9-common-dockerfile-mistakes
# Install system dependencies
RUN apt-get update -y
RUN apt-get install -y python3 python3-pip git sudo wget python3-venv

# Setup docker environment
ENTRYPOINT ["/bin/bash", "-c"]
ENV TZ="US/Pacific"
ENV PATH="${PATH}:/home/cmuser/.local/bin"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone

# Setup docker user
RUN groupadd -g $GID -o cm
RUN useradd -m -u $UID -g $GID -o --create-home --shell /bin/bash cmuser
RUN echo "cmuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER cmuser:cm
WORKDIR /home/cmuser

# Install python packages
RUN python3 -m pip install --user cmind requests giturlparse tabulate  

# Download CM repo for scripts
RUN cm pull repo anandhu-eng@cm4mlops

# Install all system dependencies
RUN cm run script --tags=get,sys-utils-cm --quiet

# Run commands
RUN cm run script --tags=run,vllm-server --model=NousResearch/Hermes-2-Theta-Llama-3-8B --api_key= --adr.cuda.version=12.4.1 --skip_docker_model_download=True --quiet --fake_run --env.CM_RUN_STATE_DOCKER=True  
