---
  resnet50:
    Offline:
      target_qps: 88000.0
    Server:
      target_qps: 73000.0
  retinanet:
    Offline:
      target_qps: 1300.0
    Server:
      target_qps: 1200
  bert-99:
    Offline:
      target_qps: 8000
    Server:
      target_qps: 6000
  bert-99.9:
    Offline:
      target_qps: 3500
    Server:
      target_qps: 3000
  3d-unet-99:
    Offline:
      target_qps: 8.0
  3d-unet-99.9:
    Offline:
      target_qps: 8.0
  gptj-99.9:
    Offline:
      target_qps: 8
    Server:
      target_qps: 7
  gptj-99:
    Offline:
      target_qps: 8
    Server:
      target_qps: 7
  sdxl:
    Offline:
      target_qps: 2
    Server:
      target_qps: 1
