---
  resnet50:
    Offline:
      target_qps: 175.0
    Server:
      target_qps: 10.0
    SingleStream:
      target_latency: 30
    MultiStream:
      target_latency: 700
  retinanet:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 300
    MultiStream:
      target_latency: 8000
  bert-99:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 10
    MultiStream:
      target_latency: 80
  bert-99.9:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 10
    MultiStream:
      target_latency: 80
