#!/bin/bash

export CM_DOCKER_BUILD_ARGS="GID=\" $(id -g $USER) \" UID=\" $(id -u $USER) \" ${CM_DOCKER_BUILD_ARGS}"
export PYTHONPATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/vision/classification_and_detection/python:/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/tools/submission:/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/get-mlperf-inference-utils:${PYTHONPATH}"
export BUILD_TRTLLM="0"
export CM_BUILD_DOCKERFILE="no"
export CM_CNNDM_ACCURACY_DTYPE="int32"
export CM_DOCKERFILE_WITH_PATH="/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference/dockerfiles/mlperf-inference:mlpinf-v4.0-cuda12.2-cudnn8.9-x86_64-ubuntu20.04-public.Dockerfile"
export CM_DOCKER_ADD_ALL_GPUS="True"
export CM_DOCKER_BUILD_ARGS="--build-arg GID=\" $(id -g $USER) \" --build-arg UID=\" $(id -u $USER) \""
export CM_DOCKER_BUILD_CMD="docker build  --build-arg GID=\" $(id -g $USER) \" --build-arg UID=\" $(id -u $USER) \" -f "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference/dockerfiles/mlperf-inference:mlpinf-v4.0-cuda12.2-cudnn8.9-x86_64-ubuntu20.04-public.Dockerfile" -t "cknowledge/cm-script-app-mlperf-inference:ubuntu-20.04-latest" ."
export CM_DOCKER_DETACHED_MODE="no"
export CM_DOCKER_EXTRA_RUN_ARGS=" --runtime=nvidia --ulimit memlock=-1 --cap-add SYS_ADMIN --cap-add SYS_TIME --security-opt apparmor=unconfined --security-opt seccomp=unconfined"
export CM_DOCKER_IMAGE_BASE="ubuntu:20.04"
export CM_DOCKER_IMAGE_NAME="cm-script-app-mlperf-inference"
export CM_DOCKER_IMAGE_RECREATE="yes"
export CM_DOCKER_IMAGE_REPO="cknowledge"
export CM_DOCKER_IMAGE_TAG="ubuntu-20.04-latest"
export CM_DOCKER_IMAGE_TAG_EXTRA="-latest"
export CM_DOCKER_INTERACTIVE_MODE="True"
export CM_DOCKER_OS="ubuntu"
export CM_DOCKER_OS_VERSION="20.04"
export CM_DOCKER_PRE_RUN_COMMANDS="['cm pull repo']"
export CM_DOCKER_RUN_CMD="cm run script --tags=app,mlperf,inference,generic,_nvidia,_sdxl,_cuda,_test,_offline --quiet=true --env.CM_QUIET=yes --env.CM_MLPERF_IMPLEMENTATION=nvidia --env.CM_MLPERF_MODEL=sdxl --env.CM_MLPERF_RUN_STYLE=test --env.CM_MLPERF_SUBMISSION_SYSTEM_TYPE=edge --env.CM_MLPERF_DEVICE=cuda --env.CM_MLPERF_USE_DOCKER=True --env.CM_MLPERF_LOADGEN_SCENARIO=Offline --env.CM_TEST_QUERY_COUNT=100 --env.CM_MLPERF_FIND_PERFORMANCE_MODE=yes --env.CM_MLPERF_LOADGEN_ALL_MODES=no --env.CM_MLPERF_LOADGEN_MODE=performance --env.CM_MLPERF_RESULT_PUSH_TO_GITHUB=False --env.CM_MLPERF_SUBMISSION_GENERATION_STYLE=full --env.CM_MLPERF_SKIP_SUBMISSION_GENERATION=yes --env.CM_MLPERF_LAST_RELEASE=v4.0 --env.CM_SUT_DESC_CACHE=no --env.CM_TMP_PIP_VERSION_STRING= --env.CM_SUT_META_EXISTS=yes --env.CM_MODEL=sdxl --env.CM_MLPERF_LOADGEN_COMPLIANCE=no --env.CM_MLPERF_LOADGEN_EXTRA_OPTIONS= --env.CM_MLPERF_LOADGEN_SCENARIOS,=Offline --env.CM_MLPERF_LOADGEN_MODES,=performance --env.CM_OUTPUT_FOLDER_NAME=test_results --add_deps_recursive.coco2014-original.tags=_full --add_deps_recursive.coco2014-preprocessed.tags=_full --add_deps_recursive.imagenet-original.tags=_full --add_deps_recursive.imagenet-preprocessed.tags=_full --add_deps_recursive.openimages-original.tags=_full --add_deps_recursive.openimages-preprocessed.tags=_full --add_deps_recursive.openorca-original.tags=_full --add_deps_recursive.openorca-preprocessed.tags=_full --v=False --print_env=False --print_deps=False --dump_version_info=True  --env.CM_MLPERF_INFERENCE_RESULTS_DIR=/home/cmuser/CM/repos/local/cache/95f7dde21294469a  --env.CM_MLPERF_INFERENCE_SUBMISSION_DIR=/home/cmuser/CM/repos/local/cache/0b32e1b297624c74/mlperf-inference-submission  --env.MLPERF_SCRATCH_PATH=/home/cmuser/CM/repos/local/cache/d8e56515079545cd  --docker_run_deps "
export CM_DOCKER_RUN_SCRIPT_TAGS="app,vision,language,mlcommons,mlperf,inference,generic"
export CM_DOCKER_SHM_SIZE="32gb"
export CM_DOCKER_VOLUME_MOUNTS="['/home/anandhu/CM/repos/local/cache/95f7dde21294469a:/home/cmuser/CM/repos/local/cache/95f7dde21294469a', '/home/anandhu/CM/repos/local/cache/0b32e1b297624c74:/home/cmuser/CM/repos/local/cache/0b32e1b297624c74', '/home/anandhu/CM/repos/local/cache/d8e56515079545cd:/home/cmuser/CM/repos/local/cache/d8e56515079545cd']"
export CM_ENV_NVMITTEN_DOCKER_WHEEL_PATH="/opt/nvmitten-0.1.3b0-cp38-cp38-linux_x86_64.whl"
export CM_IMAGENET_ACCURACY_DTYPE="int32"
export CM_LIBRISPEECH_ACCURACY_DTYPE="int8"
export CM_MLOPS_REPO="gateoverflow@cm4mlops"
export CM_MLPERF_BACKEND="tensorrt"
export CM_MLPERF_DEVICE="gpu"
export CM_MLPERF_FIND_PERFORMANCE_MODE="yes"
export CM_MLPERF_IMPLEMENTATION="nvidia"
export CM_MLPERF_INFERENCE_3DUNET_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/vision/medical_imaging/3d-unet-kits19"
export CM_MLPERF_INFERENCE_BERT_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/language/bert"
export CM_MLPERF_INFERENCE_CLASSIFICATION_AND_DETECTION_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/vision/classification_and_detection"
export CM_MLPERF_INFERENCE_CONF_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/mlperf.conf"
export CM_MLPERF_INFERENCE_DLRM_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/recommendation/dlrm"
export CM_MLPERF_INFERENCE_DLRM_V2_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/recommendation/dlrm_v2"
export CM_MLPERF_INFERENCE_GPTJ_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/language/gpt-j"
export CM_MLPERF_INFERENCE_RESULTS_DIR="/home/anandhu/CM/repos/local/cache/95f7dde21294469a"
export CM_MLPERF_INFERENCE_RESULTS_VERSION="4_1"
export CM_MLPERF_INFERENCE_RNNT_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/speech_recognition/rnnt"
export CM_MLPERF_INFERENCE_SOURCE="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference"
export CM_MLPERF_INFERENCE_SUBMISSION_DIR="/home/anandhu/CM/repos/local/cache/0b32e1b297624c74/mlperf-inference-submission"
export CM_MLPERF_INFERENCE_SUBMISSION_VERSION="4_0"
export CM_MLPERF_INFERENCE_VISION_PATH="/home/anandhu/CM/repos/local/cache/7992ff1175504e3f/inference/inference/vision"
export CM_MLPERF_LAST_RELEASE="v4.0"
export CM_MLPERF_LOADGEN_ALL_MODES="no"
export CM_MLPERF_LOADGEN_COMPLIANCE="no"
export CM_MLPERF_LOADGEN_EXTRA_OPTIONS=""
export CM_MLPERF_LOADGEN_MODE="performance"
export CM_MLPERF_LOADGEN_MODES="['performance']"
export CM_MLPERF_LOADGEN_SCENARIO="Offline"
export CM_MLPERF_LOADGEN_SCENARIOS="['Offline']"
export CM_MLPERF_MODEL="sdxl"
export CM_MLPERF_MODEL_PRECISION="float32"
export CM_MLPERF_QUANTIZATION="False"
export CM_MLPERF_RESULT_PUSH_TO_GITHUB="False"
export CM_MLPERF_RUN_STYLE="test"
export CM_MLPERF_SKIP_SUBMISSION_GENERATION="yes"
export CM_MLPERF_SUBMISSION_GENERATION_STYLE="full"
export CM_MLPERF_SUBMISSION_SYSTEM_TYPE="edge"
export CM_MLPERF_USE_DOCKER="True"
export CM_MODEL="stable-diffusion-xl"
export CM_NVIDIA_MLPERF_SCRATCH_PATH="/home/anandhu/CM/repos/local/cache/d8e56515079545cd"
export CM_NVIDIA_SCRATCH_SPACE_VERSION="4_0"
export CM_OUTPUT_FOLDER_NAME="test_results"
export CM_QUIET="yes"
export CM_REAL_RUN="True"
export CM_REGENERATE_MEASURE_FILES="yes"
export CM_RUN_STATE_DOCKER="True"
export CM_SKIP_SYS_UTILS="yes"
export CM_SQUAD_ACCURACY_DTYPE="float16"
export CM_SUT_DESC_CACHE="no"
export CM_SUT_META_EXISTS="yes"
export CM_TEST_QUERY_COUNT="100"
export CM_TMP_CURRENT_PATH="/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference"
export CM_TMP_CURRENT_SCRIPT_PATH="/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/build-docker-image"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH="/home/anandhu/CM/repos/anandhu-eng@cm4mlops"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH_WITH_PREFIX="/home/anandhu/CM/repos/anandhu-eng@cm4mlops"
export CM_TMP_CURRENT_SCRIPT_WORK_PATH="/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/app-mlperf-inference/dockerfiles"
export CM_TMP_PIP_VERSION_STRING=""
export MLPERF_SCRATCH_PATH="/home/anandhu/CM/repos/local/cache/d8e56515079545cd"


. "/home/anandhu/CM/repos/anandhu-eng@cm4mlops/script/build-docker-image/run.sh"
