name: Test Compilation of QAIC Compute SDK (build LLVM from src)

on:
  schedule:
    - cron: "1 1 * * 2"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        llvm-version: [ "12.0.1", "13.0.1", "14.0.0", "15.0.6", "16.0.4", "17.0.6" ]
        exclude:
          - llvm-version: "13.0.1"
          - llvm-version: "14.0.0"
          - llvm-version: "15.0.6"
          - llvm-version: "16.0.4"
          - llvm-version: "17.0.6"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install cmind
        cm pull repo mlcommons@cm4mlops
        cm run script --tags=get,sys-utils-cm --quiet
  
    - name: Test QAIC Compute SDK for compilation
      run: |
        cm run script --tags=get,qaic,compute,sdk --adr.llvm.version=${{ matrix.llvm-version }} --quiet
