# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CM(CK2) script automation test

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - cm-mlops/scripts/app-mlperf-inference-reference/dockerfiles
      - .github/workflows/test-mlperf-inference.yml
      - '!**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
        python3 -m pip install cmind
        cm pull repo octoml@ck
    - name: Test CM Script Automation
      run: |
        cd `cm find script --tags=app,mlperf,inference,generic,reference`/dockerfiles/retinanet &&  docker build -f onnxruntime_cpu_python_ubuntu_20.04.Dockerfile .
