# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CM script automation test for MLPerf inference resnet50 using onnxruntime

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - cm-mlops/scripts/*
      - cm-mlops/automation/*
      - .github/workflows/test-mlperf-inference-resnet50-onnxruntime.yml
      - '!**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install cmind
        cm pull repo octoml@ck
        cm run script --quiet --tags=get,sys-utils-cm
    - name: Test CM Script for MLPerf Inference ResNet50 using onnxruntime
      run: |
        cm run script --tags=run,mlperf,inference,generate-run-cmds,_submission,_short --submitter="OctoML" --hw_name=default --model=resnet50 --backend=onnxruntime --device=cpu --scenario=Offline --test_query_count=10 --quiet
