# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CM tutorial retinanet

on:
  pull_request:
    branches: [ "main", "dev", "mlperf-inference" ]
    paths:
      - '.github/workflows/test-cm-tutorial-retinanet.yml'
      - '**'
      - '!**.md'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install "cmind @ git+https://git@github.com/mlcommons/ck.git@mlperf-inference#subdirectory=cm"
        cm pull repo --url=${{ github.event.pull_request.head.repo.html_url }} --checkout=${{ github.event.pull_request.head.ref }}
        cm run script --quiet --tags=get,sys-utils-cm
    - name: Test CM Tutorial Retinanet
      run: |
        python script/test-cm-core/src/tutorials/test_tutorial_retinanet.py
