# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLPerf loadgen with HuggingFace bert onnx fp32 squad model

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/test-mlperf-loadgen-onnx-huggingface-bert-fp32-squad.yml'
      - 'cm-mlops/**'
      - '!cm-mlops/**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.9" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install cmind
        cm pull repo --url=${{ github.event.pull_request.head.repo.html_url }} --checkout=${{ github.event.pull_request.head.ref }}
        cm run script --quiet --tags=get,sys-utils-cm
    - name: Test MLPerf Inference Bert
      run: |
        cmr "python app loadgen-generic _onnxruntime _custom _huggingface _model-stub.ctuning/mlperf-inference-bert-onnx-fp32-squad-v1.1" --adr.hf-downloader.model_filename=model.onnx --quiet
